---
# tasks file for haproxy_app
#
#- name: deploy apache
hosts: apps
gather_facts: false
become: true
#tasks:
- name: install apache
  yum:
    name: httpd
    state: latest

- name: enable apache at boot
  service:
    name: httpd
    enabled: yes
