---
# tasks file for haproxy_app
#
# variable setup
#- include_vars: main.yml

- hosts: app
  include_tasks: apache_deploy.yml
  include_tasks: tomcat_deploy.yml

- hosts: frontends
  include_tasks: haproxy_deploy.yml

- hosts: appdbs
  include_tasks: postgres_deploy.yml
