---
- hosts: frontends, apps, appdbs
  roles:
    - enable_repos

#- hosts: frontends
#  become: true
#  roles:
#   - haproxy-layer

#- hosts: apps
#  become: true
#  roles:
#   - apache-layer

- hosts: appdbs
  become: true
  roles:
   - db-layer
